### ISSUE TITLE
How do you put this in dedi on ubuntu?

### ISSUE THREAD

**Issue by NoPsHeRaTuS** [HAL-NINE-THOUSAND/DMT#2]
Hello, 

I am interested in this since I need a mod that uses bmt, but I don't know how to install it on my dedicated server with ubuntu. 

and after installing in ubuntu ( if possible ), what do i need to do in my game in windows to get into my dedicated server?

Greetings.

**Comment by HAL-NINE-THOUSAND** [comment]
I think the easiest way is to use Wine
https://community.7daystodie.com/topic/14330-ubuntu-server-how-to-install-dmt/

DMT can be run from the command line using mono on linux but I haven't tried it so can't confirm it works
