### ISSUE TITLE
Harmony 2

### ISSUE THREAD

**Issue by Mythilily** [HAL-NINE-THOUSAND/DMT#3]
Since I've been waiting for a while so I thought it was worth suggesting to update harmony.
I've replaced the dll on the current DMT build and it seems to work fine, just have to make some small adjustments to patches made with 1.2.

**Comment by HAL-NINE-THOUSAND** [comment]
DMT will use Harmony 2.0 in the next release after A19 drops

Harmony 1.0 will no longer be used and old projects will need updating.
