### ISSUE TITLE
Bug with the new update?

### ISSUE THREAD

**Issue by W0lfl3g3nd1** [HAL-NINE-THOUSAND/DMT#5]
I am not sure if there is a certain format I have to put this in so forgive me.

I'm receiving an error whenever I attempt to build the mods. It only happens after the update to version 2.2.7568.19791. If I attempt to build mods with version 2.0.7486.30873, the mods build correctly without error. I have tried a fresh 7 days install and tried validating the files with steam.

Here is the error as follows along with the mods I am using (If that helps)

![7 days error](https://user-images.githubusercontent.com/65198124/93731602-99084e00-fb82-11ea-8d96-14e0a0214fea.JPG)

![7days mod](https://user-images.githubusercontent.com/65198124/93731607-9c033e80-fb82-11ea-8758-c5b232dc9559.JPG)

**Comment by HAL-NINE-THOUSAND** [comment]
Thanks for the report, the issue was fixed in the latest release so if you're still having trouble grab that copy and it should sort it.
